apiVersion: v1
kind: Pod
metadata: 
  name: service-demo-pod
 # these labels are used to register this pod with service
  labels: 
    project: roboshop
    component: frontned
    environment: dev 
spec:
  containers:
  - name: nginx
    image: nginx