apiVersion: v1
kind: Pod
metadata: 
  name: resource-demo 
spec:
  containeres:
  - name: nginx
    image: nginx
    resources:
      request:
        memory: "68Mi"
        cpu: "100m"
      #provide equal or more than requests
      limits:
        memory: "100Mi"
        cpu: "120m"