apiVersion: v1
kind: Service
metadata:
  name: demo-service-nodeport 
spec:
  type: NodePort
  selector:
    project: roboshop
    component: frontned
    environment: dev 
    purpose: nodeport
  ports: 
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port