apiVersion: v1
kind: Service
metadata:
  name: demo-service-lb 
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    component: frontned
    environment: dev 
    purpose: lb
  ports: 
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
      nodePort: 3007